### PR TITLE
Converts the remaining citra wiki links to archive.org snapshots till they're replaced.

### LINKED ISSUE #131: dead link to Citra wiki in settings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

git 274afb7

### Description of Issue

Configuration>System>How to get keys is still a link to the dead Citra site 
grafik

### Expected Behavior

Either open the corresponding page on the new wiki or open an archive link as a workaround

### Reproduction Steps

Open Lime3DS
Click on emulation in the menu bar
Click on Configure
Click on System in the left sidebar
Open the System Tab
Click on the "How to get keys?" link on the bottom

### Log File

```
[   0.398094] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.424267] Frontend <Info> lime_qt/main.cpp:GMainWindow:214: Lime3DS Version: 274afb7 | master-274afb765
[   0.424273] Frontend <Info> lime_qt/main.cpp:GMainWindow:230: Host CPU: AMD Ryzen 9 7950X 16-Core Processor             | AVX512 | FMA
[   0.424284] Frontend <Info> lime_qt/main.cpp:GMainWindow:232: Host OS: Arch Linux
[   0.424290] Frontend <Info> lime_qt/main.cpp:GMainWindow:235: Host RAM: 62.50 GiB
[   0.424291] Frontend <Info> lime_qt/main.cpp:GMainWindow:236: Host Swap: 64.00 GiB
[   0.451224] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:238: Secure1 KeyX missing
[   0.451228] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:257: Secure2 KeyX missing
[   0.451228] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:343: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   0.494977] Frontend <Warning> lime_qt/main.cpp:CheckForUpdates:1008: Unable to start check for updates
[   8.143438] Config <Info> common/settings.cpp:LogSettings:83: Citra Configuration:
[   8.143443] Config <Info> common/settings.cpp:operator():80: Core_UseCpuJit: true
[   8.143443] Config <Info> common/settings.cpp:operator():80: Core_CPUClockPercentage: 100
[   8.143444] Config <Info> common/settings.cpp:operator():80: Renderer_UseGLES: false
[   8.143444] Config <Info> common/settings.cpp:operator():80: Renderer_GraphicsAPI: OpenGL
[   8.143444] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncShaders: false
[   8.143444] Config <Info> common/settings.cpp:operator():80: Renderer_AsyncPresentation: true
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_SpirvShaderGen: true
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_Debug: false
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_UseHwShader: true
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_ShadersAccurateMul: true
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_UseShaderJit: true
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_UseResolutionFactor: 1
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_FrameLimit: 100
[   8.143445] Config <Info> common/settings.cpp:operator():80: Renderer_VSyncNew: true
[   8.143446] Config <Info> common/settings.cpp:operator():80: Renderer_PostProcessingShader: none (builtin)
[   8.143446] Config <Info> common/settings.cpp:operator():80: Renderer_FilterMode: false
[   8.143446] Config <Info> common/settings.cpp:operator():80: Renderer_TextureFilter: None
[   8.143447] Config <Info> common/settings.cpp:operator():80: Renderer_TextureSampling: GameControlled
[   8.143449] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Render3d: 0
[   8.143449] Config <Info> common/settings.cpp:operator():80: Stereoscopy_Factor3d: 0
[   8.143449] Config <Info> common/settings.cpp:operator():80: Stereoscopy_MonoRenderOption: 0
[   8.143450] Config <Info> common/settings.cpp:operator():80: Layout_LayoutOption: 0
[   8.143451] Config <Info> common/settings.cpp:operator():80: Layout_SwapScreen: false
[   8.143451] Config <Info> common/settings.cpp:operator():80: Layout_UprightScreen: false
[   8.143452] Config <Info> common/settings.cpp:operator():80: Layout_LargeScreenProportion: 4
[   8.143452] Config <Info> common/settings.cpp:operator():80: Utility_DumpTextures: false
[   8.143452] Config <Info> common/settings.cpp:operator():80: Utility_CustomTextures: false
[   8.143452] Config <Info> common/settings.cpp:operator():80: Utility_PreloadTextures: false
[   8.143452] Config <Info> common/settings.cpp:operator():80: Utility_AsyncCustomLoading: true
[   8.143452] Config <Info> common/settings.cpp:operator():80: Utility_UseDiskShaderCache: true
[   8.143452] Config <Info> common/settings.cpp:operator():80: Audio_Emulation: HLE
[   8.143453] Config <Info> common/settings.cpp:operator():80: Audio_OutputType: 0
[   8.143453] Config <Info> common/settings.cpp:operator():80: Audio_OutputDevice: auto
[   8.143453] Config <Info> common/settings.cpp:operator():80: Audio_InputType: 0
[   8.143453] Config <Info> common/settings.cpp:operator():80: Audio_InputDevice: auto
[   8.143454] Config <Info> common/settings.cpp:operator():80: Audio_EnableAudioStretching: true
[   8.143454] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightName: blank
[   8.143454] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightConfig: 
[   8.143454] Config <Info> common/settings.cpp:operator():80: Camera_OuterRightFlip: 0
[   8.143454] Config <Info> common/settings.cpp:operator():80: Camera_InnerName: blank
[   8.143455] Config <Info> common/settings.cpp:operator():80: Camera_InnerConfig: 
[   8.143455] Config <Info> common/settings.cpp:operator():80: Camera_InnerFlip: 0
[   8.143455] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftName: blank
[   8.143455] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftConfig: 
[   8.143455] Config <Info> common/settings.cpp:operator():80: Camera_OuterLeftFlip: 0
[   8.143455] Config <Info> common/settings.cpp:operator():80: DataStorage_UseVirtualSd: true
[   8.143455] Config <Info> common/settings.cpp:operator():80: DataStorage_UseCustomStorage: false
[   8.143456] Config <Info> common/settings.cpp:operator():80: System_IsNew3ds: true
[   8.143456] Config <Info> common/settings.cpp:operator():80: System_LLEApplets: false
[   8.143456] Config <Info> common/settings.cpp:operator():80: System_RegionValue: 2
[   8.143456] Config <Info> common/settings.cpp:operator():80: System_PluginLoader: false
[   8.143456] Config <Info> common/settings.cpp:operator():80: System_PluginLoaderAllowed: true
[   8.143456] Config <Info> common/settings.cpp:operator():80: Debugging_DelayStartForLLEModules: true
[   8.143457] Config <Info> common/settings.cpp:operator():80: Debugging_UseGdbstub: false
[   8.143457] Config <Info> common/settings.cpp:operator():80: Debugging_GdbstubPort: 24689
[   8.143802] Frontend <Info> lime_qt/game_list.cpp:RefreshGameDirectory:939: Change detected in the games directory. Reloading game list.
[   8.144041] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:238: Secure1 KeyX missing
[   8.144044] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:257: Secure2 KeyX missing
[   8.144045] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:343: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   8.144045] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:343: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
```

### System Configuration

CPU: AMD Ryzen 9 7950X 16-Core Processor
GPU/Driver: RX7900XT
RAM: 64GB
OS: Arch Linux
built from git using the instructions in the wiki

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #131

### CODE REVIEW

File: dist/languages/da_DK.ts [hunk 1]
```diff
@@ -2209,8 +2209,8 @@ Would you like to ignore the error and continue?</source>
     </message>
     <message>
         <location filename="../../src/lime_qt/configuration/configure_motion_touch.cpp" line="102"/>
-        <source>&lt;a href=&apos;https://citra-emu.org/wiki/using-a-controller-or-android-phone-for-motion-or-touch-input&apos;&gt;&lt;span style=&quot;text-decoration: underline; color:#039be5;&quot;&gt;Learn More&lt;/span&gt;&lt;/a&gt;</source>
-        <translation>&lt;a href=&apos;https://citra-emu.org/wiki/using-a-controller-or-android-phone-for-motion-or-touch-input&apos;&gt;&lt;span style=&quot;text-decoration: underline; color:#039be5;&quot;&gt;Lær mere&lt;/span&gt;&lt;/a&gt;</translation>
+        <source>&lt;a href=&apos;https://cemuhook.sshnuke.net/padudpserver.html&apos;&gt;&lt;span style=&quot;text-decoration: underline; color:#039be5;&quot;&gt;Learn More&lt;/span&gt;&lt;/a&gt;</source>
```
Comment (ShizCalev) [inline dist/languages/da_DK.ts]: This wiki page was never actually created and just provided you with a link to `https://cemuhook.sshnuke.net/padudpserver.html`. If you'd rather have an archive.org link for the redirecting wiki page, I'll switch it back. :)

**Comment by OpenSauce04** [comment]
I am going to redo the changes in this PR and force-push them over your branch
For future reference, translation files are not to be directly edited, as this is handled automatically by our translation service, and clang formatting errors are not to be ignored, but can instead be automatically fixed using the `git-clang-format` command

**Review by OpenSauce04 — APPROVED** [review]

**Comment by OpenSauce04** [comment]
If you were wondering, breaking a URL up across multiple lines like that works correctly
