### PR TITLE
qt: Workaround for Qt directoryChanged event spam on macOS

### LINKED ISSUE #1656: 2124.1 / macOS Tahoe 26.2 - game list flickers as if in an endless loop of loading the games
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

2124.1

### Description of Issue

Upon start the game list flickers as if it is loading the games again and again - this could sometimes be stopped by opening the Settings for example. If a game is started and then closed the list starts flickering again.

Additionally - I didn't suffer from the crash upon start up with 2124 on macOS even though I'm on 26.2.

### Expected Behavior

The game list loading does not devolve into an endless loop and flickering.

### Reproduction Steps

1. Be on macOS Tahoe 26.2
2. Start Azahar 2124.1
3. The game list flickers as if the game directory is scanned and loaded in an endless loop.

### Log File

[   0.115938] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.133003] Frontend <Info> citra_qt/citra_qt.cpp:GMainWindow:375: Azahar Version: 2124.1 | HEAD-0805711
[   0.133011] Frontend <Info> citra_qt/citra_qt.cpp:GMainWindow:392: Host OS: macOS Tahoe (26.2)
[   0.133027] Frontend <Info> citra_qt/citra_qt.cpp:GMainWindow:395: Host RAM: 36.00 GiB
[   0.133029] Frontend <Info> citra_qt/citra_qt.cpp:GMainWindow:396: Host Swap: 2.00 GiB
[   0.160300] Render.Vulkan <Info> video_core/renderer_vulkan/vk_platform.cpp:operator():271: Candidate instance extension VK_KHR_portability_enumeration is not available
[   0.224966] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.275114] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.330232] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.531904] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.563192] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.598574] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.636412] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.672066] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.717562] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.753252] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.822600] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   0.991873] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.042538] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.083654] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.114966] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.168421] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.209986] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.252063] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.289116] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.328026] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.363123] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.396204] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.427145] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.463870] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.507643] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.538716] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.580866] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.623239] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.670086] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.702901] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.737029] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.771071] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.803180] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.831526] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.868720] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.911349] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.949203] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   1.990705] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.026102] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.068086] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.108252] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.149897] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.318566] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.368374] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.414834] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.463303] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   2.510116] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.240987] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.323447] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.362114] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.398240] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.436364] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.473568] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.512104] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.552660] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.590531] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.628922] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.663660] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.696281] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.727638] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.765646] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.796591] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.834961] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.870312] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.911771] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.947166] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   7.991220] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.026861] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.067530] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.093713] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.125341] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.158582] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.191098] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.221576] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.252259] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.283076] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.317196] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.348224] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.393832] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.429712] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.471474] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.505927] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.678502] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.721568] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.761799] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.805228] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.841577] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.884924] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.920631] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.955657] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   8.996648] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.033894] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.072265] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.110850] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.145981] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.190072] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.226239] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.272733] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.308667] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.356256] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.393318] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.436528] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.471790] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.509412] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.545531] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.710645] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.751195] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.799305] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.844813] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.893287] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.936219] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[   9.985991] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.027620] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.068732] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.104744] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.146786] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.181800] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.218977] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.256200] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.303287] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.465873] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.504458] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.547834] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.587582] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.627296] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.669690] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.704763] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.747709] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.792203] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.830736] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.869887] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.913927] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.954396] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  10.996324] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.034521] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.086844] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.122099] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.164659] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.206051] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.235990] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.272999] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.312967] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.356727] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.390915] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.433326] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.478369] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.510049] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.544687] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.572843] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.605029] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.643224] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.685093] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.723182] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.762844] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.797704] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.836810] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.877203] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.925373] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  11.968568] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.009466] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.053268] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.087556] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.132937] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.178948] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.214667] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.258689] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.296166] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.339576] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.380557] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.423929] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.460872] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.504714] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.540640] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.585347] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.622024] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.657361] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.693763] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.734232] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.775667] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.821020] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.857226] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.902797] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.940951] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  12.988851] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  13.030259] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  13.074606] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  13.111259] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  13.151425] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  13.182981] Frontend <Info> citra_qt/game_list.cpp:RefreshGameDirectory:1124: Change detected in the applications directory. Reloading game list.
[  1

### System Configuration

CPU: Apple M3 Max
GPU/Driver: Apple M3 Max
RAM: 36GB
OS: macoOS 26.2

### LINKED ISSUE #1662: 2124.1 / macOS Tahoe 26.2 - Application does not react on startup
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

2124.1

### Description of Issue

On a fresh install (or after qt-config.ini is removed), if I move the application window before adding a game folder, the application becomes unresponsive and mouse pointer turns into beachball. Log files are empty.

### Expected Behavior

Application stays responsive

### Reproduction Steps

1. Ensure Azahar has not been installed on system or remove existing qt-config.ini
2. Install arm64 or universal .app file
3. Open Azahar.app
4. Move window

### Log File

Log File is empty

### System Configuration

CPU: M3 Pro
GPU/Driver: Vulkan
RAM: 36GB
OS: macOS Tahoe 26.2

### PR DESCRIPTION
**Pull request by OpenSauce04**
Closes #1662
Closes #1656

On macOS, a suspected Qt bug or some other anomaly is causing the `directoryChanged` event to re-fire when the directory hasn't actually been altered. This is triggered by `watcher` being altered in `GameList::DonePopulating`, causing an infinite loop where either the entire frontend would hang when opening or the game list would begin to violently flicker as the list refreshed itself as fast as it can.

I was only able to replicate this issue by using an application directory with at least 4 applications within it. Additionally, the bug wasn't consistent, sometimes requiring several re-launches for the issue to be seen.

This issue has been addressed by limiting the application directory to one refresh per second. If additional refreshes are attempted in this timeframe, they are ignored. This prevents the aforementioned infinite loop or hang from occurring, as after the second attempted refresh in the loop is performed, it is cancelled, allowing the application continue as normal.

In the future, the behaviour described above should be investigated, and if determined to be a Qt bug, should be reported upstream.

### CODE REVIEW

File: src/citra_qt/game_list.cpp [hunk 1]
```diff
@@ -1113,13 +1113,21 @@ const QStringList GameList::supported_file_extensions = {
...
 
 void GameList::RefreshGameDirectory() {
-
     // Do not scan directories when the system is powered on, it will be
     // repopulated on shutdown anyways.
     if (Core::System::GetInstance().IsPoweredOn()) {
         return;
     }
 
+    const auto time_now = std::chrono::system_clock::now();
```
Comment (PabloMK7) [inline src/citra_qt/game_list.cpp]: Use steady_clock instead of system_clock, which does not change depending on system time.

**Review by PabloMK7 — CHANGES_REQUESTED** [review]

**Review by PabloMK7 — APPROVED** [review]
