### PR TITLE
macOS: normalize SDMC directory filenames

### LINKED ISSUE #2079: macOS SDMC filename Unicode mismatch on accented characters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

v2125.1.1

### Description of Issue

I'm reading filenames in my homebrew in order to delete them, and the OS/macOS host path seems to be returning names as NFD (decomposed vowel + combining accent), while libctru/the guest path is using UTF-16 with the exact NFC value. This causes ENOENT.

I know this may be more nuanced than "macOS returns NFD". Maybe APFS is just preserving whatever normalization it has on disk, and macOS can still resolve equivalent names in normal lookups.

But from the guest/homebrew side, I think the important part is that if Azahar returns a filename from SDMC directory reading, that same filename should work later for delete/rename/open. Right now it looks like some host-side Unicode normalization detail is leaking into the emulated SDMC filesystem.

I could normalize it in my homebrew just in case someone is using Azahar, but I think it makes more sense to fix it in the emulator instead.

I can try to prepare a small PR if this is considered a valid emulator-side bug.

### Expected Behavior

A filename returned by SDMC directory enumeration should be usable later by the guest for operations such as delete/remove, even if the host filesystem uses a different Unicode normalization form.

### Reproduction Steps

1. Open 3dslibris debug 3dsx v2.6.0 (I left this intentionally unfixed on purpose)
2. Have a book with accented vowels on your system
3. Go to Settings -> Next page -> Clear Cache
4. See the logs and notice some items fail to be removed

### Log File

The log I'm seeing in my homebrew:

[2026-04-28 09:44:07] [INFO][GEN] DeleteDirContents: remove failed path=sdmc:/3ds/3dslibris/cache/covers/Brieva,_Day,_Pilhofer_-_Teorￃﾭa_Musical_para_Dummies_-_2010_696d2580.cvr rc=-1 errno=2
[2026-04-28 09:44:07] [INFO][GEN] DeleteDirContents: remove failed path=sdmc:/3ds/3dslibris/cache/covers/Pokeￌﾁmon_Mystery_Dungeon~_Silver_Resistance_-_The_Anthology_v.4.2_aa9ed241.cvr rc=-1 errno=2

### System Configuration

CPU: Apple M1 Pro
GPU/Driver: Apple M1 Pro
RAM: 16GB
OS: macOS 15.7.5
Software: 3dslibris
Affected files: generated .cvr cover/cache files with accented characters

### PR DESCRIPTION
**Pull request by RigleGit**
- [X] I have read the [Azahar AI Policy document](https://github.com/azahar-emu/azahar/blob/master/AI-POLICY.md) and have disclosed any use of AI if applicable under those terms.
---------

---

Ignore Until Your PR has been created!
---

This PR fixes #2079. 

Tested with my homebrew on macOS 15.7.5, and not it works perfectly.

**AI disclosure**: I used ChatGPT/Codex (GPT-5.5 Low) to help me understand the issue, discuss possible locations in the filesystem code, and review some code. The final patch was reviewed, edited and tested manually.

### CODE REVIEW

**Comment by RigleGit** [comment]
@RigleGit Azahar

File: src/common/string_util.cpp [hunk 1]
```diff
@@ -164,6 +170,62 @@ std::u16string UTF8ToUTF16(std::string_view input) {
     return boost::locale::conv::utf_to_utf<char16_t>(input.data(), input.data() + input.size());
 }
 
+// macOS filesystems may expose decomposed Unicode names through directory listings.
+// Normalize to NFC before passing names to guest APIs that expect stable text.
+std::string NormalizeUTF8ToNFC(std::string_view input) {
```
Comment (PabloMK7) [inline src/common/string_util.cpp]: Can you change this function name a bit? The name `NormalizeNFDToNFC` seems more appropriate.

File: src/core/file_sys/disk_archive.cpp [hunk 2]
```diff
@@ -62,22 +64,25 @@ u32 DiskDirectory::Read(const u32 count, Entry* entries) {
 
     while (entries_read < count && children_iterator != directory.children.cend()) {
         const FileUtil::FSTEntry& file = *children_iterator;
-        const std::string& filename = file.virtualName;
+        // Directory entries are exposed to the guest as UTF-16. Normalize host UTF-8 names first
+        // so host Unicode normalization differences do not leak into guest-visible SDMC paths.
+        const std::string filename = Common::NormalizeUTF8ToNFC(file.virtualName);
```
Comment (PabloMK7) [inline src/core/file_sys/disk_archive.cpp]: I think this should be put between #ifdefs APPLE, as well as the entire normalize function itself. That way it is not left in the executable when not needed.

File: src/core/file_sys/disk_archive.cpp [hunk 3]
```diff
@@ -93,4 +98,5 @@ u32 DiskDirectory::Read(const u32 count, Entry* entries) {
     return entries_read;
 }
 
+
```
Comment (PabloMK7) [inline src/core/file_sys/disk_archive.cpp]: Unneccessary newline?

**Review by PabloMK7 — CHANGES_REQUESTED** [review]
Thanks for the chnage! A few minor notes.

**Comment by RigleGit** [comment]
Done. 
* `NormalizeNFDToNFC` is declared, defined, and called only under `#if defined(__APPLE__)`. 
* Non-Apple builds keep using the original filename directly.

**Comment by PabloMK7** [comment]
Looks like you forgot to adapt the test case to remove the case when apple is not defined.

**Comment by RigleGit** [comment]
Whoops, done

**Comment by PabloMK7** [comment]
LGTM, but please fix the detected license and format failures.

**Comment by RigleGit** [comment]
Let's see if everything is alright now

**Review by PabloMK7 — APPROVED** [review]

**Comment by PabloMK7** [comment]
@RigleGit please next time make sure you don't replace existing copyright notices of other projects (`string_util.cpp`). Partially my fault too as I didn't notice the dolphin copyright being removed. I have force pushed to ammend the commit and fix the license to not have a commit with a broken license in the history.

**Comment by RigleGit** [comment]
@PabloMK7 sorry about that, and thanks for fixing it.

I updated the license headers because the license check was failing and I understood that it was required to make the PR pass. 

I didn’t want to remove existing copyright notices from other projects, so I’ll keep that in mind for future PRs. Thanks again!
