### PR TITLE
fix compilation on older QT6

### LINKED ISSUE #168: Azahar installation error
Could be due to a different QT version on the system?

```
[ 94%] Building CXX object src/citra_qt/CMakeFiles/citra_qt.dir/citra_qt.cpp.o
[ 94%] Building CXX object src/citra_qt/CMakeFiles/citra_qt.dir/configuration/configure_motion_touch.cpp.o
[ 94%] Building CXX object src/citra_qt/CMakeFiles/citra_qt.dir/configuration/configure_system.cpp.o
/home/jagbai/azahar/src/citra_qt/configuration/configure_motion_touch.cpp:233:48: error: no member named 'checkStateChanged' in 'QCheckBox'
  233 |     connect(ui->touchpad_checkbox, &QCheckBox::checkStateChanged, this,
      |                                     ~~~~~~~~~~~^
1 error generated.
make[2]: *** [src/citra_qt/CMakeFiles/citra_qt.dir/build.make:949: src/citra_qt/CMakeFiles/citra_qt.dir/configuration/configure_motion_touch.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3481: src/citra_qt/CMakeFiles/citra_qt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 95%] Built target tests
make: *** [Makefile:166: all] Error 2
[91mCompilation failed[39m

[91mFailed to install Azahar![39m
[40m[93m[5m🔺[25m[39m[49m[93mNeed help? Copy the [1mENTIRE[0m[49m[93m terminal output or take a screenshot.
Please ask on GitHub: [94m[4mhttps://github.com/cobalt2727/L4T-Megascript/issues[24m[93m
Or on Discord: [94m[4mhttps://discord.gg/abgW2AG87Z[0m
```

### PR DESCRIPTION
**Pull request by cobalt2727**
---
Follows the structure at https://github.com/azahar-emu/azahar/pull/441 inside configure_motion_touch. I haven't tested it yet, but this should resolve https://github.com/cobalt2727/L4T-Megascript/issues/168 without breaking anything for anyone.

---

### CODE REVIEW

**Comment by cobalt2727** [comment]
my username is cobalt2727 and the logo is from the Azahar project

File: src/citra_qt/configuration/configure_cheats.cpp [hunk 1]
```diff
@@ -60,11 +60,11 @@ void ConfigureCheats::LoadCheats() {
             i, 2, new QTableWidgetItem(QString::fromStdString(cheats[i]->GetType())));
         enabled->setProperty("row", static_cast<int>(i));
 
-#if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
+    #if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
```
Comment (OpenSauce04) [inline src/citra_qt/configuration/configure_cheats.cpp]: Preprocessor operations aren't indented.

**Review by OpenSauce04 — CHANGES_REQUESTED** [review]

File: src/citra_qt/configuration/configure_motion_touch.cpp [hunk 2]
```diff
@@ -230,8 +230,14 @@ void ConfigureMotionTouch::ConnectEvents() {
             poll_timer->start(200);     // Check for new inputs every 200ms
         }
     });
-    connect(ui->touchpad_checkbox, &QCheckBox::checkStateChanged, this,
-            [this]() { UpdateUiDisplay(); });
+    #if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
```
Comment (OpenSauce04) [inline src/citra_qt/configuration/configure_motion_touch.cpp]: Same here

**Review by OpenSauce04 — CHANGES_REQUESTED** [review]

**Review by OpenSauce04 — APPROVED** [review]
LGTM
