### PR TITLE
android: Fix IOFile::GetFd not functioning as expected in vanilla

### LINKED ISSUE #1850: Cheats not loading
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

2125.0-alpha5-vanilla

### Description of Issue

When loading a game with a cheats file there are no cheats to select in azahar

### Expected Behavior

Cheats show up and can be enabled

### Reproduction Steps

1. Add cheat to a game
2. Exit azahar completely (not in multitasking menu)
3. Open azahar and launch game with the cheat added
4. Cheats will not be there

### Log File

[azahar_log.old.txt](https://github.com/user-attachments/files/25846517/azahar_log.old.txt)

### System Configuration

CPU: Snapdragon 8 gen 2
GPU/Driver: adreno 740/ Mr. Purple Turnip T24
RAM: 12 gb
OS: Android 13

### PR DESCRIPTION
**Pull request by OpenSauce04**
Closes #1850 

This fixes the cheats menu not loading correctly.

This commit additionally contains some extra logging and a minor cleanup step in `AndroidStorage::TranslateFilePath` which shouldn't affect anything but is best practice.

### CODE REVIEW

File: src/common/file_util.h [hunk 1]
```diff
@@ -438,13 +439,16 @@ class IOFile : public NonCopyable {
         if (m_file == nullptr)
             return -1;
         return fileno(filestream_get_vfs_handle(m_file)->fp);
-#elif defined(ANDROID)
-        return m_fd;
 #else
+#ifdef ANDROID
```
Comment (PabloMK7) [inline src/common/file_util.h:445]: This is not the proper way to fix the bug, the problem is that we forgot to populate m_fd in the `Open()` code. In fact this function can be made simpler by doing so on all OSes. For now this works as a temporary solution.

**Review by PabloMK7 — APPROVED** [review]
