### PR TITLE
MacOS: fix(network): fixes ArticBase UDP buffer handling on macOS

### LINKED ISSUE #816: Artic Controller does not function on macOS
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

2120.1

### Description of Issue

When connecting to Artic Base with my Mac, the Artic Controller feature does not recognize any input. The Artic Controller feature is enabled in the options, and the 3DS running Artic Base clearly shows on the bottom screen that the Artic Controller mode is enabled, but no inputs register. The game itself runs, but I am unable to get past the title screen. When connecting to Artic Base without Artic Controller enabled, the standard Azahar gamepad configuration works.

### Expected Behavior

The controller buttons I press on my 3DS should be reflected on the emulator while connected.

### Reproduction Steps

Run Azahar, enable the Artic Controller option, and connect to a 3DS running Artic Base.

### Log File

[azahar_log.txt](https://github.com/user-attachments/files/19440604/azahar_log.txt)

### System Configuration

CPU: Apple M2 Pro
GPU/Driver: Vulkan
RAM: 16GB
OS: macOS 14.6.1

### PR DESCRIPTION
**Pull request by AlexMolina08**
Fixes ArticBase controller input reliability issues on macOS:

- Set minimum 8KB UDP receive buffer size on macOS for reliable operation
- Add platform-specific buffer size handling with conditional compilation
- Enhance error logging with errno details and buffer size verification
- Maintain backward compatibility with existing buffer sizes on other platforms

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Closes #816

File: src/network/artic_base/artic_base_client.cpp [hunk 1]
```diff
@@ -143,15 +144,40 @@ void Client::UDPStream::Handle() {
...
+    int actual_buffer_size;
+    if (::getsockopt(main_socket, SOL_SOCKET, SO_RCVBUF,
+                     reinterpret_cast<char*>(&actual_buffer_size), &actual_size_len) == 0) {
+#ifdef __APPLE__
+        LOG_INFO(Network, "macOS UDP buffer size set to: {} (requested: {})", actual_buffer_size,
+                 effective_buffer_size);
+#else
+        LOG_DEBUG(Network, "UDP buffer size set to: {} (requested: {})", actual_buffer_size,
+                  effective_buffer_size);
+#endif
```
Comment (OpenSauce04) [inline src/network/artic_base/artic_base_client.cpp]: Isn't this distinction kind of redundant? Why would you need to specify that it's running on MacOS in the log message when that would be evident from the fact that the user is... Using MacOS.

Also, why does the type of logging differ here? (`INFO` vs `DEBUG`)

**Review by PabloMK7 — APPROVED** [review]
