### PR TITLE
Flatpak shortcut creation fixes

### LINKED ISSUE #340: Lime3DS fails to create game shortcuts on desktop and applications menu in Linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 2116

### Description of Issue

Whenever I try to create a shortcut for a game in Lime3DS, it shows an error for creating a shortcut for desktop and application menu.
Screenshot_20240807_161844
Screenshot_20240807_161931
 

### Expected Behavior

It should create a direct game shortcut on the desktop or in the application menu, i.e when you open the shortcut, it should directly launch the game.

### Reproduction Steps

1. Open Lime3DS
2. Right click on any 3DS game, then Create Shortcut>Add to Desktop/ Add to Application Menu

https://github.com/user-attachments/assets/942f1042-480e-4c58-b577-f7e3ae37fd97

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16523531/lime3ds_log.txt)

### System Configuration

Laptop: ASUS TUF Gaming A15 FA506IHRB-HN080W
CPU: AMD Ryzen 5 4600H 6C/12T 3.0GHz
GPU/Driver: NVIDIA GeForce GTX 1650 Mobile 4GB GDDR6 (using the proprietary nvidia-driver-550, a.k.a Nvidia-G06 driver in openSUSE)
RAM: Samsung 8GB single channel DDR4 RAM at 3200 MHz
OS: openSUSE Tumbleweed 20240806 on Linux 6.10 kernel
DE: KDE Plasma 6.1.3
WM: X11

### PR DESCRIPTION
**Pull request by OpenSauce04**
Closes #340

- [x] Fix desktop shortcut creation
  - [x] Fix shortcut creation failing if icons directory structure doesn't exist
  - [x] Fix Flatpak sandbox not having access to ~/Desktop
    - https://github.com/flathub/io.github.lime3ds.Lime3DS/pull/26
  - [x] Fix the `Exec` and `TryExec` sections of shortcuts created with the Flatpak being incorrect
- [x] Fix application menu shortcut creation
  - [x] Figure out reason for and fix shortcut creation failing
  - [x] Update Flatpak sandbox permissions to allow access to applications directory
    - https://github.com/flathub-infra/flatpak-builder-lint/pull/466
    - https://github.com/flathub/io.github.lime3ds.Lime3DS/pull/29
- [x] Testing
  - [x] Linux
  - [x] Windows

### CODE REVIEW

**Comment by OpenSauce04** [comment]
~Waiting on https://github.com/flathub/io.github.lime3ds.Lime3DS/pull/29 building successfully before merging, which may take a couple of hours to build correctly as I'm waiting for our access exception to go live on Flathub's end.~
~The code here will remain unchanged, so this code is ready for review.~

The aforementioned PR has been merged successfully

File: src/lime_qt/main.cpp [hunk 1]
```diff
@@ -1819,7 +1821,7 @@ bool GMainWindow::CreateShortcutLink(const std::filesystem::path& shortcut_path,
         LOG_ERROR(Frontend, "Failed to create IShellLinkW instance");
         return false;
     }
-    hres = ps1->SetPath(command.c_str());
+    hres = ps1->SetPath(Common::UTF8ToUTF16W(command).data());
```
Comment (ghost) [inline src/lime_qt/main.cpp:1822]: What's this change for?

File: src/lime_qt/main.cpp [hunk 2]
```diff
@@ -1918,19 +1920,27 @@ bool GMainWindow::MakeShortcutIcoPath(const u64 program_id, const std::string_vi
...
-    std::filesystem::path citra_command = args[0].toStdString();
-    // If relative path, make it an absolute path
-    if (citra_command.c_str()[0] == '.') {
-        citra_command = FileUtil::GetCurrentDir().value_or("") + DIR_SEP + citra_command.string();
+    std::string lime_command{};
+    bool skip_tryexec = false;
+    const char* env_flatpak_id = getenv("FLATPAK_ID");
+    if (env_flatpak_id) {
+        lime_command = fmt::format("flatpak run {}", env_flatpak_id);
+        skip_tryexec = true;
```
Comment (ghost) [inline src/lime_qt/main.cpp:1933]: What would happen if a game rom file got deleted and a user tries to open the shortcut of that game since this is being skipped

File: src/lime_qt/main.cpp (hunk 1 above)
Comment (OpenSauce04) [reply src/lime_qt/main.cpp:1822]: MSYS2 compilation fails when trying to convert `char*` to `wchar_t*`, and this resolves the issue. This same function call is performed for other strings in the same code block, so I used them as reference.

File: src/lime_qt/main.cpp (hunk 2 above)
Comment (OpenSauce04) [reply src/lime_qt/main.cpp:1935]: Opening the .desktop file simply doesn't do anything, as you'd expect. `TryExec` is an optional value.

File: src/lime_qt/main.cpp (hunk 1 above)
Comment (ghost) [reply src/lime_qt/main.cpp:1822]: Ok than i see

File: src/lime_qt/main.cpp (hunk 2 above)
Comment (OpenSauce04) [reply src/lime_qt/main.cpp:1933]: TryExec here refers to a value in the .desktop file, and doesn't have anything to do with ROM loading in the emulator itself. The emulator likely just throws an error stating that the ROM doesn't exist or whatever it has always done.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
All looks good to me.
