### PR TITLE
Replace/remove leftover links for citra website and API #1236

### LINKED ISSUE #1236: Old Citra URLs
### Issue

As the title says, I found a few URL's that still point to the old Citra website as well as some APIs that were part of Citra's web infrastructure. Some are just comments, others reference things like the Citra accounts and profiles system (which as far as I know Azahar currently does not provide an alternative nor I know if you plan on bringing back).

You can easily find them by searching the terms ["citra-emu.org"] and ["community.citra-emu.org"] on the repository's code.

["citra-emu.org"]:https://github.com/search?q=repo%3Aazahar-emu%2Fazahar+citra-emu.org&type=code&p=1
["community.citra-emu.org"]:https://github.com/search?q=repo%3Aazahar-emu%2Fazahar+https%3A%2F%2Fcommunity.citra-emu.org&type=code

The one in particular that made me actually report this is the fatal error's crash dialog as this may move away people to the wrong place and report bugs might be lost, as the user can't know how to properly report them:

Image

Which is located here:
https://github.com/azahar-emu/azahar/blob/980f8e02e50fd8769cc4d21b274493eab684ae5d/src/citra_qt/citra_qt.cpp#L3433

### PR DESCRIPTION
**Pull request by RedBlackAka**
Replace leftover links to the Citra website with matching ones from archive.org and remove placeholder links for Citra's old web service API. Closes #1236.

### CODE REVIEW

File: src/citra_qt/configuration/config.cpp [hunk 1]
```diff
@@ -872,29 +871,13 @@ void QtConfig::ReadUILayoutValues() {
     qt_config->endGroup();
 }
 
-void QtConfig::ReadWebServiceValues() {
-    qt_config->beginGroup(QStringLiteral("WebService"));
-
-    NetSettings::values.web_api_url =
-        ReadSetting(QStringLiteral("web_api_url"), QStringLiteral("https://api.citra-emu.org"))
```
Comment (PabloMK7) [inline src/citra_qt/configuration/config.cpp]: None of the web service settings should be removed, there are currently third party services that allow using multiplayer rooms, and those require changing these settings manually.

**Review by PabloMK7 — CHANGES_REQUESTED** [review]

**Review by PabloMK7 — APPROVED** [review]
